# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
            
    - name: Run MSBuild
      run: msbuild build\RetroCode\RetroCode.sln -property:Configuration=Release

    - name: Run Test
      run: msbuild /t:RetroCore.Test build\RetroCode\RetroCore.Test\RetroCore.Test.vcxproj -property:Configuration=Release

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure() 
      with:
        name: CppUnit Tests
        path: build\RetroCode\RetroCore.Test\result.xml 
        reporter: cppunit
